name: Compute Volleyball Leaderboards

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy

      - name: Run volleyball compute script
        run: python compute/compute_rtg.py

      - name: Commit and push updated leaderboards
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/leaderboard_men_2025.csv data/leaderboard_women_2025.csv
          git commit -m "Auto-update volleyball leaderboards [skip ci]" || echo "No changes to commit"
          git fetch origin main
          git pull --rebase origin main
          git push origin main
